{% set name = "metadynamics_analysis" %}

package:
  name: {{ name|lower }}
  version: {{ environ['VERSION'] }}

source:
  git_rev: "v0.5"
  git_url: https://github.com/owenvickery/metadynamics_analysis

requirements:
  run:
    - scipy
    - numpy
    - pathlib
    - matplotlib
    - numba

build:
  number: {{ environ.get("GIT_DESCRIBE_NUMBER", 0) }} #{{ environ['GIT_DESCRIBE_HASH'] }} 
  script_env:
    - VERSION
    - CONDA_BLD_PATH
    - package
run:
  - python

extra:
  maintainers:
    - Owen Vickery
